[server]
# debug 开发模式; release 生产模式
AppMode = debug
# 监听地址和端口
HttpPort = :3000
# JWT加盐字符串
JwtKey = 89js82js72@a=KCAFJWQER012
# 登录密码加盐字符串
PwdKey = aoefqCINAETCA
# 服务器、Git密码模式下的key
ServerGitKey = a&D*71&FBA12-9P*
# 秘钥文件存储目录
KeyFilePath = data/go_deployment_system/upload/key
# 代码存放目录
CodePath = data/go_deployment_system/git

[database]
# 数据库类型需要为MySQL
# 数据库连接地址
DbHost = 10.0.1.51
# 数据库连接端口
DbPort = 3306
# 数据库连接账号
DbUser = root
# 数据库连接密码
DbPassWord = 123456
# 数据库名称
DbName = go_deployment_system

[log]
# 日志文件存储目录
LogPath = data/go_deployment_system/log
# 日志文件名称
LogFileName = ops.log
# 日志最大保存时间 单位:天
LogSaveTime = 10
# 日志切割大小 单位:MB
LogSplitSize = 10
